services:
  docs:
    networks: [workwatch]
    build:
      context: .
      dockerfile: Dockerfile
    image: workwatch-docs
    container_name: docs
    restart: unless-stopped
    ports:
      - '4173:80'

networks:
  workwatch:
